POST http://127.0.0.1:8000/chat HTTP/1.1
content-type: application/json

{
    "model": "gpt-3.5-turbo",
    "messages": [{
        "role": "user",
        "content": "これから私は何を糧に生きていけばよいのでしょうか？"
    }]
}